version: "3.8"
services:
  ansible:
    build:
      context: ./
      dockerfile: dockerfile-ansible
    image: ansible
    container_name: ansible
    hostname: ansible
    environment:
      TZ: Asia/Tokyo
    tty: true
    restart: always
    volumes:
      - ansible:/opt/ansible
    working_dir: /opt/ansible
volumes:
  ansible:
    driver: local
